export const initFiveSeconds = {
  gameStarted: false,
  numLives: 2,
  gameStarter: -1,
  gameRound: 0,
  roundRound: -1,
  roundComplete: false,
  roundStarted: false,
  roundRoundStarted: false,
  roundRoundComplete: false,
  voteStarted: false,
  voteCompleted: false,
  playerPassed: false,
  pass: 0,
  fail: 0,
  gameMode: 'hardcore',
  gameState: 'setup',
  players: [],
  gameData: [],
};
