service: games-night-api-fiveseconds
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables
provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  apiGateway:
    websocketApiId: bq7auya367
  region: eu-west-1
  environment:
    usersTableName: GamesNightUsers
    sessionsTableName: GamesNightSessions
    s3BucketName: games-night-data
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 'arn:aws:dynamodb:eu-west-1:*:*'
    - Effect: 'Allow'
      Action: '*'
      Resource: 'arn:aws:s3:::games-night-data/*'
    - Effect: 'Allow'
      Action: '*'
      Resource: 'arn:aws:execute-api:eu-west-1:*:*'

##################### Five Second Rule Routes ##########################
functions:
  fiveseconds-playerJoin:
    handler: lambdas/playerJoin.main
    events:
      - websocket:
          route: fivesecondsplayerjoin
  fiveSeconds-livesChange:
    handler: lambdas/livesChange.main
    events:
      - websocket:
          route: fivesecondsliveschange
  fiveSeconds-dataReset:
    handler: lambdas/dataReset.main
    events:
      - websocket:
          route: fivesecondsdatareset
  fiveSeconds-stateChange:
    handler: lambdas/stateChange.main
    events:
      - websocket:
          route: fivesecondsstatechange
  fiveSeconds-endGame:
    handler: lambdas/endGame.main
    events:
      - websocket:
          route: fivesecondsendgame
  fiveSeconds-startRound:
    handler: lambdas/startRound.main
    events:
      - websocket:
          route: fivesecondstartround
  fiveSeconds-endQuestion:
    handler: lambdas/endQuestion.main
    events:
      - websocket:
          route: fivesecondendquestion
  fiveSeconds-vote:
    handler: lambdas/vote.main
    events:
      - websocket:
          route: fivesecondvote
  fiveSeconds-result:
    handler: lambdas/result.main
    events:
      - websocket:
          route: fivesecondresult
